### ISSUE TITLE
Responsive tablet grid

### ISSUE THREAD

**Issue by Clarice-COD** [Clarice-COD/look-and-feel-corporate-identity#13]
Ik heb geleerd een grid te maken met minmax via de onderstaande link die ik van een mentor heb gekregen:
https://ishadeed.com/article/css-grid-minmax/

```CSS
/* AGENDA GRID */

.agenda-products{
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(220px, 1fr));
    grid-gap: 0rem 2rem;
    margin-left: 2rem;
    margin-right: 2rem;
}

.agenda-product-1, .agenda-product-2, .agenda-product-3, .agenda-product-4{
    color: var(--primary-text-color);
    border-radius: 1.5rem;

    & p{
        margin-top: 0;
        width: auto;
        align-self: center;
    }

    & h2{
        align-self: end;
        font-size: 1.4rem;
        color: var(--primary-text-color);
    }
}

.agenda-product-1{
    background-image: linear-gradient(to bottom, rgba(0, 0, 0, 0), rgba(0, 0, 0, 0.678)),
    url(./assets/ZADEN.webp);
    background-position: center;
    background-size: cover;
}

.agenda-product-2{
    background-image: linear-gradient(to bottom, rgba(0, 0, 0, 0), rgba(0, 0, 0, 0.678)),
    url(./assets/fiets\ met\ plant.webp);
    background-position: center;
    background-size: cover;
}

.agenda-product-3{
    background-image: linear-gradient(to bottom, rgba(0, 0, 0, 0), rgba(0, 0, 0, 0.678)),
    url(./assets/Aardbei.png);
    background-position: center;
    background-size: cover;
}

.agenda-product-4{
    background-image: linear-gradient(to bottom, rgba(0, 0, 0, 0), rgba(0, 0, 0, 0.678)),
    url(./assets/schuur.webp);
    background-position: center;
    background-size: cover;
}

.agenda-product-details{
    display: grid;
    grid-template-rows: 17rem auto 4rem;
    text-align: left;

    & h2{

    }

    & p{
        margin: 0;
        max-width: 9rem;
    }
}
```

<img width="600" alt="tablet responsive" src="https://github.com/user-attachments/assets/1e9712cc-0532-4806-a4e9-25d2fc1caa2e">
